ENH Add workflow permissions
silverstripe/gha-ci pull request #118
Opened 2024-04-16 02:23 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-framework/issues/10510

2024-04-16 21:10 UTC, GuySartorelli requested changes

2024-04-16 21:10 UTC, GuySartorelli commented on .github/workflows/ci.yml
The list you provided in https://github.com/silverstripe/silverstripe-framework/issues/10510#issuecomment-2055406330 says this for `ci.yml` jobs:


> context - none
> genmatrix - none
> tests - none
> checkgovernance - none
> patchrelease - contents:write <<<---- note this will affect ALL repos that use ci.yml

Can you please confirm why this file doesn't have all of those permissions defined?

2024-04-17 06:23 UTC, emteknetnz commented on .github/workflows/ci.yml
This (permissions: contents: write) is specifically for the auto-tag workflow on the gha-ci repo. It has nothing to do with ci.yml jobs.

What is does relate to is this in the comment:

```
gha-auto-tag
    required_permissions: contents:write
    uses_gha_actions: gha-tag-release
```

which itself uses this action

```
gha-tag-release
    required_permissions: contents:write
    uses_gha_actions: none
```

2024-04-17 06:29 UTC, emteknetnz commented on .github/workflows/ci.yml
patchrelease is defined

don't need to define the 'none' permissions because they're defined as none by `{}` by the top level permissions node

2024-04-17 21:53 UTC, GuySartorelli commented on .github/workflows/ci.yml
Oh yup good point 😂 I'm a wally

2024-04-17 21:54 UTC, GuySartorelli approved these changes
LGTM, will merge will all the other associated PRs when they're all approved

2024-04-17 21:55 UTC, merged