DOC Add note about permissions to readme
silverstripe/gha-ci pull request #138
Opened 2024-07-28 21:55 UTC by GuySartorelli

Anyone who wants to use this with their own modules will need to set the correct permissions, so we should show them how and let them know about possible security implications.

## Issue
- https://github.com/silverstripe/gha-ci/issues/137

2024-07-28 23:55 UTC, emteknetnz requested changes
Ack

In gha-ci we already set [permissions: {}](https://github.com/silverstripe/gha-ci/blob/1/.github/workflows/ci.yml#L54) and [individual permissions](https://github.com/silverstripe/gha-ci/blob/1/.github/workflows/ci.yml#L1058) on jobs

Have we validated that setting `contents: write` in the module level ci.yml is quickly overwritten to the `permissions: {}` in the shared-workflow ci.yml?

Cos otherwise, `contents: write` seems like very risky thing to ask people to set?  GitHub actions by default will set `contents: read` for pull-requests, I'm not sure if this would overwrite that, though I think it would?

2024-07-28 23:59 UTC, GuySartorelli commented
> In gha-ci we already set [permissions: {}](https://github.com/silverstripe/gha-ci/blob/1/.github/workflows/ci.yml#L54) and [individual permissions](https://github.com/silverstripe/gha-ci/blob/1/.github/workflows/ci.yml#L1058) on jobs

Right, and that works for everything in the silverstripe org because of the overly-permissive permissions I mentioned in the PR description. We're basically bypassing the permission requirements anyway.
> Workflows have read and write permissions in the repository for all scopes.

> Have we validated that setting contents: write in the module level ci.yml is quickly overwritten to the permissions: {} in the shared-workflow ci.yml?

I don't know what you mean by that - but I did test that `contents: read` wasn't sufficient, and that `contents: write` works as expected in my own repo https://github.com/GuySartorelli/silverstripe-composable-validators/actions/runs/10135116386

2024-07-29 00:13 UTC, GuySartorelli commented
I guess the other option is to split out the gha-tag-release part into its own job? So CI would trigger a new workflow for tagging instead of directly using that action as part of the CI workflow?

2024-07-29 00:53 UTC, emteknetnz commented
> We're basically bypassing the permission requirements anyway.

I don't think that's true, there was a lot of trial and error to get those permissions correct. It wasn't simply a case of "everything has write permissions by default therefore its work"

What I don't quite understand is that things work fine on the actions on the creative-commoners account, so it's possibly not a cross-org issue?

> I guess the other option is to split out the gha-tag-release part into its own job?

Yeah I think that's probably a good idea, that should entirely remove the need to worry about `contents: write`.

We already 'trigger' other workflows in other places e.g. https://github.com/silverstripe/gha-trigger-ci/blob/1/action.yml#L81

2024-07-29 01:54 UTC, GuySartorelli commented
> What I don't quite understand is that things work fine on the actions on the creative-commoners account, so it's possibly not a cross-org issue?

As mentioned in the issue description and clarified in person, this is because we're using "Read and write permissions" instead of "Read repository contents and packages permissions" - which means that we don't have to declare permissions directly in the `ci.yml` file. It seems that the initial permissions of the token are validated early on, and any permissions downstream in the shared workflow file or actions files are validated only if the initial validation passes.

>> I guess the other option is to split out the gha-tag-release part into its own job?
>
>Yeah I think that's probably a good idea

I'll proceed with that.

2024-07-29 23:50 UTC, GuySartorelli commented
Gonna do that in a separate PR.

2024-07-29 23:50 UTC, closed without merging