FIX Case insensitive match pre-stable versions
silverstripe/gha-ci pull request #158
Opened 2024-10-17 21:31 UTC by emteknetnz

Issue https://github.com/silverstripe/.github/issues/320

2024-10-21 22:07 UTC, GuySartorelli requested changes
Where'd the capitalisation come from? `5.3@RC.x-dev` isn't even a valid constraint. It looks like there's something upstream that needs fixing.

2024-10-21 23:19 UTC, emteknetnz commented
Upstream would be composer I think?  This only happens on a --prefer-lowest install

2024-10-22 03:17 UTC, GuySartorelli commented
Discussed in person - composer is giving us something like `^5.3@RC` and we're removing the caret and adding `.x-dev`.

2024-10-22 03:17 UTC, GuySartorelli approved these changes
LGTM

2024-10-22 03:17 UTC, merged