FIX Handle beta1 tags
silverstripe/gha-ci pull request #62
Opened 2023-03-13 05:31 UTC by emteknetnz

Issue https://github.com/silverstripe/.github/issues/23

2023-03-13 20:52 UTC, GuySartorelli requested changes
It doesn't work for stable tags either (e.g. https://github.com/silverstripe/silverstripe-framework/actions/runs/4042593676/jobs/6966612050)
Technically that's covered in https://github.com/silverstripe/gha-ci/issues/54 but these two issues are basically duplicates of one another.

If it's trivial to do, please fix stable tags as well (if not, we can do it under the other card)

2023-03-14 23:23 UTC, emteknetnz commented
@GuySartorelli Added support for stable tags

2023-03-14 23:29 UTC, GuySartorelli approved these changes

2023-03-14 23:29 UTC, merged

2023-03-14 23:30 UTC, GuySartorelli commented
Tagged as [1.3.3](https://github.com/silverstripe/gha-ci/releases/tag/1.3.3)